In [1]:
import requests
from bs4 import BeautifulSoup
import os
#import pandas to convert list to data frame
import pandas as pd

In [2]:
html_target = "a"
tag = "href"
f_ext = ".pdf"
dir_name = "Ghodsi_Ali"
url = "http://www.deux-zero.com/index.php?Code=L1&Item=Stades&Edition=2017-2018&StadeId=229"

In [3]:
r = requests.get(url)

status = r.status_code
encoding = r.encoding
html_doc = r.text

soup = BeautifulSoup(html_doc, 'html.parser')
anchor = soup(html_target)

In [4]:
#print(soup.prettify())
right_td=soup.find('td',class_="SousCadre")

In [5]:
G=[]
tbody = soup.findAll(class_='Txt11')[1]
tbody

In [6]:
A=[]
B=[]
C=[]
D=[]
E=[]
F=[]


for row in right_td.findAll("tr",class_="LigneMatch"):
    cells = row.findAll("td")
    A.append(str(cells[0].text))
    B.append(str(cells[2].text))
    C.append(str(cells[3].text))
    D.append(str(cells[4].text))
    E.append(str(cells[6].text))
    F.append(str(cells[6].text))
    G.append(tbody.text)

In [7]:
df=pd.DataFrame(A,columns=['Date'])
df['Domicile']=B
df['Résultat']=C
df['exterieur']=D
df['Affluence']=E
df['Capacite']=G

df['Date'].apply(lambda x: x[len(x)+0:len(x)-5])

df['Capacite'] = df['Capacite'].str.replace('places','')
df['Capacite'] = df['Capacite'].str[:5]

file_name="LYON.csv"

#df.to_csv(file_name)
pd.read_csv(file_name).append(df).drop_duplicates().to_csv(file_name, sep=',', encoding='utf-8',index=False)

df

,Date,Domicile,Résultat,exterieur,Affluence,Capacite
0,1ère journée sam 05-08-2017 20:00,Olympique Lyonnais,4-0,RC Strasbourg Alsace,39177,59186
1,3ème journée sam 19-08-2017 17:00,Olympique Lyonnais,3-3,FC Girondins de Bordeaux,42073,59186
2,5ème journée dim 10-09-2017 17:00,Olympique Lyonnais,2-1,EA Guingamp,36697,59186
3,7ème journée sam 23-09-2017 20:00,Olympique Lyonnais,3-3,Dijon FCO,33600,59186
4,9ème journée ven 13-10-2017 20:45,Olympique Lyonnais,3-2,AS Monaco FC,43295,59186
5,11ème journée dim 29-10-2017 15:00,Olympique Lyonnais,2-0,FC Metz,53921,59186
6,13ème journée dim 19-11-2017 17:00,Olympique Lyonnais,0-0,Montpellier Hérault SC,47651,59186
7,15ème journée mer 29-11-2017 19:00,Olympique Lyonnais,1-2,Lille OSC,31679,59186
8,18ème journée dim 17-12-2017 21:00,Olympique Lyonnais,2-0,Olympique de Marseille,57206,59186
9,20ème journée dim 14-01-2018 17:00,Olympique Lyonnais,1-1,Angers SCO,36691,59186
10,22ème journée dim 21-01-2018 21:00,Olympique Lyonnais,2-1,Paris Saint-Germain FC,57582,59186
11,25ème journée dim 11-02-2018 21:00,Olympique Lyonnais,0-2,Stade Rennais FC,39188,59186
12,27ème journée dim 25-02-2018 17:00,Olympique Lyonnais,1-1,AS Saint-Etienne,58069,59186
13,29ème journée dim 11-03-2018 17:00,Olympique Lyonnais,1-0,SM Caen,39530,59186
14,31ème journée dim 01-04-2018 21:00,Olympique Lyonnais,2-0,Toulouse FC,48548,59186
15,33ème journée sam 14-04-2018 17:00,Olympique Lyonnais,3-0,Amiens SC,47513,59186
16,35ème journée sam 28-04-2018 17:00,Olympique Lyonnais,2-0,FC Nantes,50443,59186
17,36ème journée dim 06-05-2018 16:30,Olympique Lyonnais,3-0,ESTAC Troyes,54273,59186
18,38ème journée sam 19-05-2018 21:00,Olympique Lyonnais,3-2,OGC Nice,56953,59186